<?php if(!Mage::getBaseUrl()){?>
<?php if(Mage::helper('downloads')->isEnabled()): ?>

<div id="downloads_video_popup">
    <div class="popup-cont">
        <div id="dl_video_content">
            <div id="dl_video_title">
                <h2>video title</h2>
            </div>
            <div id="dl_video">
                video content
            </div>
        </div>
        <div id="dl-spinner" class="spinner"></div>
        <div type="button" id="close_popup" class="close-button"></div>
    </div>
</div>
<!--<div id="downloads_video_overlay"></div>-->
<script type="text/javascript">
    downloads.postInit();
</script>

<?php endif; ?>
<?php }?>